openapi: 3.0.3
info:
  title: 4thon-team19 API
  version: 1.0.0
servers:
  - url: /
    description: Local

paths:
  /api/health:
    $ref: './paths/users.yaml#/paths/~1api~1health'
  /api/guest:
    $ref: './paths/users.yaml#/paths/~1api~1guest'

  # 배틀모드
  /api/battle/rooms:
    $ref: './paths/battle.yaml#/paths/~1api~1battle~1rooms'
  /api/battle/{sessionId}/start:
    $ref: './paths/battle.yaml#/paths/~1api~1battle~1{sessionId}~1start'

  # 연습모드
  /api/practice/start:
    $ref: './paths/practice.yaml#/paths/~1api~1practice~1start'
  /api/practice/{sessionId}/answer:
    $ref: './paths/practice.yaml#/paths/~1api~1practice~1{sessionId}~1answer'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref: './components/schemas.yaml'
  responses:
    $ref: './components/responses.yaml'
